
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes: jdxj
    tagName: shirley:v0.1.0
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/dev"
        tables: "shares"
  build:
    arch: "arm64,amd64"
    system: "darwin,linux"